# Generated by Django 4.2 on 2025-12-13 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_article_comment_ecoconnect_event_greenbusiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoconnect',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='ecoconnect_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
